Repository atom-community/atom-languageclient, pull requests merged in 2021-03, with the labels that each got.

#131 chore: update @types/atom
  lib/utils.ts
  package.json
  pnpm-lock.yaml
  typings/atom/index.d.ts
Labels: dependencies

#130 test: simplify autocomplete-paths tests by removing createCompletionItem
  test/adapters/autocomplete-adapter.test.ts
Labels: tests

#133 refactor: clean-up module augments
  lib/adapters/notifications-adapter.ts
  lib/utils.ts
  package.json
  pnpm-lock.yaml
  typings/atom/index.d.ts
Labels: dependencies

#134 test: improve autocomplete tests by using a unified getSuggestionsMock
  test/adapters/autocomplete-adapter.test.ts
Labels: tests

#122 feat: Upgrade to LSP 3.16
  lib/adapters/autocomplete-adapter.ts
  lib/adapters/document-sync-adapter.ts
  lib/auto-languageclient.ts
  lib/languageclient.ts
  package.json
  pnpm-lock.yaml
  test/adapters/autocomplete-adapter.test.ts
  test/helpers.ts
Labels: enhancement, high-priority

#129 Feature: handling custom requests
  lib/languageclient.ts
Labels: enhancement, waiting-for-review

#138 chore: add more properties and TODOs
  lib/auto-languageclient.ts
  lib/convert.ts
Labels: waiting-for-review

#136 Autocomplete improvements
  lib/adapters/autocomplete-adapter.ts
  lib/auto-languageclient.ts
  test/adapters/autocomplete-adapter.test.ts
Labels: enhancement, waiting-for-review

#135 feat: implement window/showDocument
  lib/adapters/show-document-adapter.ts
  lib/auto-languageclient.ts
  lib/languageclient.ts
  test/adapters/show-document-adapter.test.ts
  test/fixtures/hello.ts
  typings/electron/index.d.ts
Labels: enhancement
