Repository atom-community/atom-languageclient, pull requests merged in 2021-05, with the labels that each got.

#150 Added null check to some adapters and changed type definition
  lib/adapters/code-action-adapter.ts
  lib/adapters/code-highlight-adapter.ts
  lib/adapters/outline-view-adapter.ts
  lib/auto-languageclient.ts
  lib/languageclient.ts
  package.json
  pnpm-lock.yaml
  test/languageclient.test.ts
Labels: bug

#154 use atom-jasmine3-test-runner
  .eslintrc.json
  lib/auto-languageclient.ts
  package.json
  pnpm-lock.yaml
  test/adapters/apply-edit-adapter.test.ts
  test/adapters/autocomplete-adapter.test.ts
  test/adapters/code-action-adapter.test.ts
  test/adapters/code-format-adapter.test.ts
  test/adapters/code-highlight-adapter.test.ts
  test/adapters/command-execution-adapter.test.ts
  test/adapters/custom-linter-push-v2-adapter.test.ts
  test/adapters/datatip-adapter.test.ts
  test/adapters/document-sync-adapter.test.ts
  test/adapters/linter-push-v2-adapter.test.ts
  test/adapters/outline-view-adapter.test.ts
  test/adapters/show-document-adapter.test.ts
  test/adapters/signature-help-adapter.test.ts
  test/auto-languageclient.test.ts
  test/convert.test.ts
  test/helpers.ts
  test/languageclient.test.ts
  test/runner.js
  test/utils.test.ts
Labels: tests

#155 chore: update devDependencies
  lib/adapters/apply-edit-adapter.ts
  lib/adapters/autocomplete-adapter.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies

#153 feat: add support for workspace folders
  .gitignore
  lib/auto-languageclient.ts
  lib/languageclient.ts
  lib/server-manager.ts
  package.json
  pnpm-lock.yaml
  test/auto-languageclient.test.ts
  test/helpers.ts
  typings/atom/index.d.ts
Labels: enhancement

#139 feat: initial code actions backend for Linter service
  lib/adapters/code-action-adapter.ts
  lib/adapters/diagnostic-adapter.ts
  lib/adapters/linter-push-v2-adapter.ts
  lib/convert.ts
  lib/languageclient.ts
  test/adapters/code-action-adapter.test.ts
  test/adapters/diagnostics-adapter-test.ts
  test/adapters/linter-push-v2-adapter.test.ts
  typings/atom/index.d.ts
Labels: enhancement
