Repository atom-community/atom-languageclient, pull requests merged in 2021-02, with the labels that each got.

#120 fix: use zadeh library
  lib/adapters/autocomplete-adapter.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies

#117 feat: API for registering custom callbacks for Commands
  lib/adapters/code-action-adapter.ts
  lib/adapters/command-execution-adapter.ts
  lib/main.ts
  test/adapters/command-execution-adapter.test.ts
Labels: enhancement

#123 fix: fix type errors when atom-languageclient is used with TypeScript
  lib/adapters/autocomplete-adapter.ts
  lib/types/autocomplete-extended.ts
  package.json
  pnpm-lock.yaml
  test/adapters/autocomplete-adapter.test.ts
  tsconfig.json
  typings/atom-ide/index.d.ts
Labels: bug

#124 feat: add functions for spawning a general executable + allow custom handlers for lsProcess + fix LanguageServerProcess type
  README.md
  lib/auto-languageclient.ts
  lib/main.ts
  lib/server-manager.ts
  lib/utils.ts
  test/utils.test.ts
Labels: enhancement
